
// Action Types for Display Reducer
export const WELCOME_SCREEN = 'WELCOME_SCREEN';
export const HOME_SCREEN = 'HOME_SCREEN';
export const CALENDAR_SCREEN = 'CALENDAR_SCREEN';

export const MEDICATION_LIST = 'MEDICATION_LIST';
export const MEDICATION_DETAIL = 'MEDICATION_DETAIL';
export const MEDICATION_EDIT = 'MEDICATION_EDIT';
export const MEDICATION_CREATE = 'MEDICATION_CREATE';

export const APPOINTMENT_LIST = 'APPOINTMENT_LIST';
export const APPOINTMENT_DETAIL = 'APPOINTMENT_DETAIL';
export const APPOINTMENT_EDIT = 'APPOINTMENT_EDIT';
export const APPOINTMENT_CREATE = 'APPOINTMENT_CREATE';

export const QOL_LIST = 'QOL_LIST';
export const QOL_DETAIL = 'QOL_DETAIL';
export const QOL_CREATE = 'QOL_CREATE';
export const QOL_EDIT = 'QOL_EDIT';

